const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {Game}=require('../web/core.js'),FpsRoom=require('../web/fps.js');
const data=vm.runInNewContext(fs.readFileSync('web/assets.js','utf8')+';MINIT_ASSETS');
function fixture(){const game=new Game(data);game.continuous=true;game.enemySpawnRemaining=9999;game.pilot={x:519,y:48,floor:62,inside:true,vy:0,pose:'idle'};const room=new FpsRoom(game);room.sync();return {game,room};}
const {game,room}=fixture();assert.equal(room.maps.length,7);room.move(room.player,-100,0);assert.ok(room.player.x>.2);assert.equal(room.clear(6.5,7.5),false);
room.player.x=11;room.player.z=3;room.player.yaw=Math.PI/2;
game.enemies=[{x:668,y:48,state:1,hits:0,animation:0,action:'base',phase:'inside',fps:{x:11,z:6,level:0},canShoot:false}];
room.shoot();assert.equal(room.flash,.1);assert.equal(room.recoil,1);assert.ok(room.hitMarker>0);assert.ok(game.enemies[0].hitFlash>0);
for(let i=0;i<2;i++){room.cooldown=0;room.shoot();}assert.equal(game.enemies.length,0);assert.equal(game.mines.length,1);assert.equal(game.mines[0].fps.z,6);assert.ok(room.effects.some(e=>e.kind==='explosion'));
const stairs=fixture();for(let level=0;level<6;level++){const s=stairs.room.stairs(level).find(s=>s.kind==='down');Object.assign(stairs.room.player,{x:s.x,z:s.z});delete stairs.room.player.stairLock;stairs.room.step({},1/60);assert.ok(stairs.room.transition);for(let i=0;i<37;i++)stairs.room.step({},1/60);assert.equal(stairs.room.player.level,level+1);assert.equal(stairs.room.transition,null);stairs.room.step({},1/60);assert.equal(stairs.room.transition,null);}assert.equal(stairs.room.player.level,6);
const objective=fixture();objective.room.player.x=20;objective.room.player.z=2;objective.game.enemies=[{x:668,y:48,state:1,hits:0,animation:0,action:'base',phase:'inside',canShoot:false}];for(let i=0;i<26000&&objective.game.enemies.length;i++)objective.room.step({},1/60);assert.equal(objective.game.computerHits,1);assert.equal(objective.game.enemies.length,0);
const cover=fixture();cover.room.bullets=[{x:5.8,z:7.5,vx:6,vz:0,level:0}];cover.room.step({},.2);assert.equal(cover.room.bullets.length,0);
const separate=fixture();separate.room.player.x=11;separate.room.player.z=3;separate.room.player.yaw=Math.PI/2;separate.game.enemies=[{state:1,hits:0,phase:'inside',fps:{x:11,z:6,level:1}}];separate.room.shoot();assert.equal(separate.game.enemies[0].hits,0);
const launch=fixture();Object.assign(launch.room.player,{level:6,x:19,z:14});launch.game.missileSlots[0]='loaded';launch.room.step({interact:true},1/60);assert.equal(launch.game.launchedMissiles,1);Object.assign(launch.room.player,{level:0,x:3,z:2});launch.room.step({},1/60);launch.room.step({interact:true},1/60);assert.equal(launch.room.active,false);assert.equal(launch.game.pilot.inside,false);
console.log('PASS: seven floors, alternating stairs and arrival lock, cover, combat feedback, floor isolation, robot path to computer, launch and exit');
const access=fixture();access.room.leave();assert.equal(access.game.pilot.x,519);assert.equal(access.game.pilot.floor,45);access.room.sync();assert.equal(access.room.active,false);
Object.assign(access.game.pilot,{x:670,y:71,floor:85,inside:false});access.game.fpsInterior=true;access.game.customZones={collisions:[{x:540,y:85,w:153,h:2}],teleports:[],teleportDistance:13};access.game.cockpit();access.room.sync();assert.equal(access.room.player.level,2);assert.equal(access.room.player.x,19);assert.equal(access.room.player.z,9);
access.room.step({interact:true},1/60);assert.equal(access.room.active,false);assert.equal(access.game.pilot.inside,false);assert.equal(access.game.pilot.x,670);assert.equal(access.game.pilot.y,71);assert.equal(access.game.pilot.floor,85);access.room.sync();assert.equal(access.room.active,false);
access.game.stepPilot({down:true},1/60);access.room.sync();assert.equal(access.room.active,false);access.game.stepPilot({},1/60);access.game.cockpit();access.room.sync();assert.equal(access.room.player.level,2);
console.log('PASS: roof exit, third-floor side entry/exit with custom zones, no automatic reentry, held-input lock and reentry');
const projection=fixture();for(let level=0;level<7;level++){const f=projection.room.projectionFrame(level),atStart=projection.room.project({...f.entry,level}),atEnd=projection.room.project({...f.target,level});assert.equal(atStart.progress,0);assert.equal(atEnd.progress,1);assert.equal(atStart.x,f.from);assert.equal(atEnd.x,f.to);assert.equal(atEnd.y,48+level*13);}
const shared=fixture();shared.game.enemies=[{x:519,y:48,state:2,hits:1,animation:0,action:'base',phase:'inside',canShoot:false}];shared.room.player.x=20;shared.room.player.z=2;for(let i=0;i<300;i++)shared.room.step({},1/60);const robot=shared.game.enemies[0],position=robot.fps,oldX=robot.x;assert.equal(robot.hits,1);assert.equal(robot.x,shared.room.project(position).x);shared.room.leave();for(let i=0;i<300;i++)shared.room.step({},1/60);assert.equal(robot.fps,position);assert.notEqual(robot.x,oldX);assert.equal(robot.hits,1);shared.game.pilot.inside=true;shared.game.pilot.floor=62;shared.game.pilot.y=48;shared.room.sync();assert.equal(robot.fps,position);assert.equal(robot.hits,1);shared.room.leave();shared.game.pilot=null;for(let i=0;i<26000&&shared.game.enemies.length;i++)shared.room.step({},1/60);assert.equal(shared.game.computerHits,1);
const takeover=fixture();takeover.room.leave();takeover.game.pilot=null;takeover.game.enemies=[{x:519,y:48,state:3,hits:2,animation:0,action:'base',phase:'walking'}];takeover.game.stepEnemies(1/60);takeover.room.step({},1/60);assert.equal(takeover.game.enemies[0].phase,'inside');assert.ok(takeover.game.enemies[0].fps);assert.equal(takeover.game.enemies[0].hits,2);const dead=takeover.game.enemies[0];takeover.game.destroyEnemy(dead,true);assert.equal(takeover.game.mines[0].fps.level,0);assert.equal(takeover.game.enemies.length,0);
console.log('PASS: distance projection on seven floors, shared enemy identity/hits across views, exterior descent and computer damage, canonical takeover and mine');
const live=fixture();live.room.leave();live.game.pilot=null;live.game.enemies=[{x:519,y:48,state:1,hits:0,animation:0,action:'base',phase:'walking',canShoot:false}];for(let i=0;i<26000&&live.game.enemies.length;i++){live.game.step({});live.room.step({},1/60);}assert.equal(live.game.computerHits,1);assert.equal(live.game.enemies.length,0);
console.log('PASS: complete live game loop advances indoor enemy to computer while player is in 2D');
const explicit=fixture();explicit.room.leave();explicit.game.pilot.vy=0;assert.equal(explicit.game.fpsEntrance(),'roof');explicit.game.stepPilot({down:true},1/60);explicit.room.sync();assert.equal(explicit.room.active,false);explicit.game.cockpit();explicit.room.sync();assert.equal(explicit.room.active,true);assert.equal(explicit.room.player.level,0);explicit.room.leave();Object.assign(explicit.game.pilot,{x:670,y:71,floor:85,vy:0});assert.equal(explicit.game.fpsEntrance(),'side');explicit.game.stepPilot({down:true},1/60);explicit.room.sync();assert.equal(explicit.room.active,false);explicit.game.cockpit();explicit.room.sync();assert.equal(explicit.room.player.level,2);explicit.room.leave(explicit.room.sideExit);explicit.game.pilot.x=600;assert.equal(explicit.game.fpsEntrance(),null);explicit.game.cockpit();explicit.room.sync();assert.equal(explicit.room.active,false);
console.log('PASS: E-only entry at roof and third floor, S never enters, distant E never enters');
for(const [x,roof,expected]of [[519,41,'roof'],[670,81,'side'],[519,49,'roof'],[670,89,'side']]){const shifted=fixture();shifted.room.leave();shifted.game.customZones={collisions:[{x:x-30,y:roof,w:80,h:2}],teleports:[]};Object.assign(shifted.game.pilot,{x,y:roof-14,vy:0,inside:false});assert.equal(shifted.game.fpsEntrance(),expected);shifted.game.step({cockpit:true});shifted.room.sync();assert.equal(shifted.room.active,true);assert.equal(shifted.room.player.level,expected==='roof'?0:2);}
console.log('PASS: E entry through actual game.step at both entrances on shifted custom collision floors');
const seam=fixture();for(let level=0;level<6;level++){const stair=seam.room.downStair(level),above=seam.room.project({...stair,level}),below=seam.room.project({...stair,level:level+1});assert.equal(below.x,above.x);assert.equal(below.y,above.y+13);}const third=seam.room.project({...seam.room.downStair(1),level:2});assert.equal(third.x,513);assert.equal(third.y,74);assert.ok(third.x<540);
console.log('PASS: stair descent preserves projected X on all six seams; third floor arrives inside at X513');
